from Config import *
from pymongo import MongoClient

client = MongoClient(DB_DEV_IP)
mydb = client[DB_SCHEMA]

class IMIST_AMBO:

	def __init__(self):
		self.mytable = mydb[IMIST_AMBO_TEMPLATE]
		
		self.map_keyword_category = [
			{"keyword": "age",
			 "category": "identification"},
			{"keyword": "male",
			 "category": "identification"},
			{"keyword": "female",
			 "category": "identification"},
			{"keyword": "mca",
			 "category": "mechanism"},
			{"keyword": "rollover",
			 "category": "mechanism"},
			{"keyword": "eject",
			 "category": "mechanism"},
			{"keyword": "death other occupant",
			 "category": "mechanism"},
			{"keyword": "pedestrian",
			 "category": "mechanism"},
			{"keyword": "motorcyclist",
			 "category": "mechanism"},
			{"keyword": "cyclist",
			 "category": "mechanism"},
			{"keyword": "fall",
			 "category": "mechanism"},
			{"keyword": "burn",
			 "category": "mechanism"},
			{"keyword": "explosion",
			 "category": "mechanism"},
			{"keyword": "trapped",
			 "category": "mechanism"},
			{"keyword": "time entrapped",
			 "category": "mechanism"},
			{"keyword": "mba",
			 "category": "mechanism"},
			{"keyword": "extrication",
			 "category": "mechanism"},
			{"keyword": "fatality",
			 "category": "mechanism"},
			{"keyword": "ejection",
			 "category": "mechanism"},
			{"keyword": "penetrate",
			 "category": "injury"},
			{"keyword": "blunt",
			 "category": "injury"},
			{"keyword": "head",
			 "category": "injury"},
			{"keyword": "neck",
			 "category": "injury"},
			{"keyword": "chest",
			 "category": "injury"},
			{"keyword": "abdomen",
			 "category": "injury"},
			{"keyword": "pelvis",
			 "category": "injury"},
			{"keyword": "axilla",
			 "category": "injury"},
			{"keyword": "groin",
			 "category": "injury"},
			{"keyword": "limb",
			 "category": "injury"},
			{"keyword": "amputation",
			 "category": "injury"},
			{"keyword": "crush",
			 "category": "injury"},
			{"keyword": "spinal",
			 "category": "injury"},
			{"keyword": "tension pneumothorax",
			 "category": "injury"},
			{"keyword": "rigid abdomen",
			 "category": "injury"},
			{"keyword": "fracture",
			 "category": "injury"},
			{"keyword": "pelvis",
			 "category": "injury"},
			{"keyword": "facial burn",
			 "category": "injury"},
			{"keyword": "dislocation",
			 "category": "injury"},
			{"keyword": "evisceration",
			 "category": "injury"},
			{"keyword": "blast",
			 "category": "injury"},    
			{"keyword": "pr",
			 "category": "signs"},
			{"keyword": "bp",
			 "category": "signs"},
			{"keyword": "gcs",
			 "category": "signs"},
			{"keyword": "evm",
			 "category": "signs"},
			{"keyword": "pupil size",
			 "category": "signs"},
			{"keyword": "reactivity",
			 "category": "signs"},
			{"keyword": "rr",
			 "category": "signs"},
			{"keyword": "t degree",
			 "category": "signs"},
			{"keyword": "spo 2",
			 "category": "signs"},
			{"keyword": "sob",
			 "category": "signs"},
			{"keyword": "sbp",
			 "category": "signs"},
			{"keyword": "cervical collar",
			 "category": "treatment"},
			{"keyword": "op airway",
			 "category": "treatment"},
			{"keyword": "np airway",
			 "category": "treatment"},
			{"keyword": "lma",
			 "category": "treatment"},
			{"keyword": "ett",
			 "category": "treatment"},
			{"keyword": "rsi",
			 "category": "treatment"},
			{"keyword": "ventilate",
			 "category": "treatment"},
			{"keyword": "chest decompress",
			 "category": "treatment"},
			{"keyword": "iv access",
			 "category": "treatment"},
			{"keyword": "iv hartmanns",
			 "category": "treatment"},
			{"keyword": "methoxyflurane",
			 "category": "treatment"},
			{"keyword": "maxolon",
			 "category": "treatment"},
			{"keyword": "morphine",
			 "category": "treatment"},
			{"keyword": "midazolam",
			 "category": "treatment"},
			{"keyword": "fentanyl",
			 "category": "treatment"},
			{"keyword": "suxamethonium",
			 "category": "treatment"},
			{"keyword": "pancuronium",
			 "category": "treatment"},
			{"keyword": "adrenaline",
			 "category": "treatment"},
			{"keyword": "intubation",
			 "category": "treatment"},
			{"keyword": "haemostatic dressing",
			 "category": "treatment"},
			{"keyword": "toumiquet",
			 "category": "treatment"},
			{"keyword": "blood transfusion",
			 "category": "treatment"},
			{"keyword": "neuromuscular blockade",
			 "category": "treatment"},
			{"keyword": "allergy",
			 "category": "other"},
			{"keyword": "mass casualty",
			 "category": "other"},
			{"keyword": "inter-hospital transfer",
			 "category": "other"},
			{"keyword": "pregnancy",
			 "category": "other"},
			{"keyword": "co-morbid",
			 "category": "other"},
			{"keyword": "anticoagulant therapy",
			 "category": "other"}
			]

	def insert(self):
		self.mytable.insert(self.map_keyword_category)

if __name__=='__main__':
	imist_ambo = IMIST_AMBO()
	imist_ambo.insert()
